### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Michael-E238** [Michael-E238/Pre-Work-Study-Guide#1]
# HTML

## User Story

As a bootcamp student
I want the prework notes to be structured on a web page
So I can easily find a read information

## Acceptance Criteria

GIVEN a prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by Nishant9771** [comment]
There are some Listed Websites where you can check once : 
1. freecodecamp
2. MDN WEB
3. codecademy
4. coursera
5. w3school
6. or last you can explore any repositories regading that on github.
